# Generated by Django 3.2.3 on 2021-06-04 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('one_supply', models.FloatField(default=0)),
                ('unit', models.CharField(default='g', max_length=10)),
                ('total_supply', models.FloatField(default=0)),
                ('kcal', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbohydrate', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('before_menu1', models.FloatField(default=0)),
                ('before_menu2', models.FloatField(default=0)),
                ('before_menu3', models.FloatField(default=0)),
                ('before_menu4', models.FloatField(default=0)),
                ('before_menu5', models.FloatField(default=0)),
                ('after_menu1', models.FloatField(default=0)),
                ('after_menu2', models.FloatField(default=0)),
                ('after_menu3', models.FloatField(default=0)),
                ('after_menu4', models.FloatField(default=0)),
                ('after_menu5', models.FloatField(default=0)),
                ('eaten', models.FloatField(default=0)),
                ('eaten_menu1', models.FloatField(default=0)),
                ('eaten_menu2', models.FloatField(default=0)),
                ('eaten_menu3', models.FloatField(default=0)),
                ('eaten_menu4', models.FloatField(default=0)),
                ('eaten_menu5', models.FloatField(default=0)),
                ('kcal', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbohydrate', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('food', models.ManyToManyField(blank=True, related_name='diets', to='foods.Food')),
                ('menu1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_munu1', to='foods.food')),
                ('menu2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_munu2', to='foods.food')),
                ('menu3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_munu3', to='foods.food')),
                ('menu4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_munu4', to='foods.food')),
                ('menu5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_munu5', to='foods.food')),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
