# Generated by Django 3.2.3 on 2021-06-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='kcal',
        ),
        migrations.AlterField(
            model_name='diet',
            name='carbohydrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='fat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='protein',
            field=models.FloatField(null=True),
        ),
    ]
