# Generated by Django 3.2.3 on 2021-06-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20210605_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='carbohydrate',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='protein',
        ),
    ]
