# Generated by Django 3.2.3 on 2021-05-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('bio', models.TextField(blank=True, default='')),
            ],
        ),
    ]
